### ISSUE TITLE
Domain limits need to be established

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#1]
The config.xml currently allows access to ALL domains. This should be limited to a particular set of domains:
- DEV: *.masas-sics.ca
- MASAS-X: *.masas-x.ca (NOTE: do NOT make this change until we are ready for live data - may add each domain individually - training.masas-x.ca, exercise.masas-x.ca, etc.)
- others?

**Comment by GabeF** [comment]
We can add all the related domains as individual entries in the config.xml.  As more domains are available, you would add them and push an updated to the app.

**Comment by GabeF** [comment]
This has been done in the latest build since BES 10 didn't allow for a "ALL" domain access.
