### ISSUE TITLE
Popup - consider Details and Attachments button

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#10]
Getting from the Map to the details for an Entry/Alert is laborious and non-intuitive. Putting in a 
Details link (button?) and Attachments link (button?) in the popup would make the action much more obvious to the user.

**Comment by GabeF** [comment]
Added a "Details" and "Cancel" button in 5e9395623e71c852c91c28f239dd7761814e3242.

The attachments could be done... for that I'll leave this open for now.
