### ISSUE TITLE
Show Icon for Polygon and Line based Entries

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#11]
Currently if an Entry is line or polygon based there is no symbol shown on the map. Implement something similar to the JavaScript viewer where it draws the icon somewhere on the screen. I think the rules are as follows:
- if the polygon is covering the whole screen put it into the centre of the screen.
- if the polygon is partially on the screen or fully contained put the icon in the centroid of the visible polygon.

If that is too complex (i.e. takes too much time) use one of the polygon's on-screen vertices.

**Comment by GabeF** [comment]
The second point is implemented in 4afe8072cda9ad0111e0c156b38b67fd2977f6a9.

**Comment by GabeF** [comment]
The first point is implemented in b0ce4a5dcbae6cd2bebeca20210f370d386a4687.
