### ISSUE TITLE
Check Ins - position is hard-coded

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#12]
Testing the Check In process (screens look good) - the position seems to be hard-coded to the Sarnia Airport (georss:point42.999444 -82.308889/georss:point).

I was having trouble with the location (GPS wasn't engaging) and attempted a location search (nothing returned) but my location search wasn't in Sarnia (it was my home address).

**Comment by GabeF** [comment]
I'll look into the GPS/Location issues....

As for the hard-coded value.  There is a "default" location being used (hard-coded); I'll add an entry in the settings to modify it.

**Comment by GabeF** [comment]
This is now fixed in 42c1dc969c7f0d696af074f2ec0658099eb4cf57.
Hard-coded value is now accessible via the Settings page.
