### ISSUE TITLE
Polygon "point" (icon) is not clickable in map

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#13]
The Polygon points (the icon for a polygon) should act/react like the point-based entries. Clicking, for example, on a point representing a weather event (typically a polygon) should show the same popup and highlight the item.

**Comment by GabeF** [comment]
Have you tried this on the PlayBook or iPad?

**Comment by darrellodonnell** [comment]
well, there just may be a chance (a good one) that my FAT FINGERS missed
the icon...
