### ISSUE TITLE
Field Report - "Notes" field un-necessary

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#2]
The Field Report page has Title, Description, and Notes.

The MASAS Entry (ATOM) only uses Title (<title> block) and Description (<content> block). There is no place for Notes. Remove it please.

**Comment by GabeF** [comment]
Not a problem.  "Notes" from the application was being pushed to the "Summary" block at this point.

**Comment by GabeF** [comment]
Removed in commit: d93c5558ddd0760987614fdf70c4c57d49d36039.
