### ISSUE TITLE
Field Report - Need Configured Values

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#3]
The concept behind the messages sent is that the device should be aware of "who" or "what" is sending the message and add that bit of information to what is sent.

Example 1: Officer arrives on Scene:
Officer Bloggins arrives on scene and files a personnel-related field report. His device is configured to report as a "Police Car" with identity "Car 57". He types in a Field Report "Initial Observations" (title) and "Arrived onscene. No people in vicinity. Noise coming from house - music and shouting." 

The app, when it submits adds the appropriate info:
- title: Initial Observations [Car 57]
- description: Arrived onscene. No people in vicinity. Noise coming from house - music and shouting.
  icon: 

Icon choices would be:
- Police: ems/operations/lawEnforcement/policeCar
- Fire: operations/emergencyFire/fireTruck
- EMS: ems/operations/emergencyMedical/ambulance

**Comment by GabeF** [comment]
These have been added in commit 89b71539b9117d30ff529130a40db5c123f478b0.
