### ISSUE TITLE
Entry - only ADDs are done.

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#5]
The check-in is not clearing out old items (or updating them) resulting in numerous entries. This concept needs to have a lifecycle.

As an officer moves around the system should keep his/her position active - not leave an immense number of old entries that look like current ones.

The Check-In/Out capability really needs to be about that particular user and should use an Update mechanism with Lifecycle. The Check In to a site starts the life of a CheckIn (using MASAS Entry). Subsequent updates would update that Entry. On Check-Out  that entry has reached end-of-life and a subsequent checkin is a new entry.

IDEA: Use a "Check In" button to create the entry, and change it to Update Check-In while that entry is still alive.

If a Check-in expires (use same time as the MASAS Entry expiry the user will need to Check-In again at that site. 

If a user does a Check-In (as opposed

**Comment by GabeF** [comment]
Implemented the new concept in 0215a3a87e61286b9e354e0f6d749567b2b2c9bd.
