### ISSUE TITLE
Polygon alerts not showing symbol

### ISSUE THREAD

**Issue by darrellodonnell** [darrellodonnell/masas-mobile#7]
The polygon alerts (e.g. Weather) are not showing on the map with the icon. The approach that we have taken in the past is that for a polygon or line the icon will show at the centroid of the item - unless the centroid is off screen in which case it would show in the centroid of what is visible.

Further, clicking on the icon should display the underlying line/polygon.

**Comment by GabeF** [comment]
Fix in issue #11
